#!/usr/bin/env python3
"""Generate a C translation unit containing the project's Ogg assets."""

import argparse
import re
from pathlib import Path


def c_identifier(path: str) -> str:
    name = re.sub(r"[^A-Za-z0-9_]", "_", path)
    if name and name[0].isdigit():
        name = "_" + name
    return "mybot_asset_" + name


def emit_bytes(data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return "\n".join(lines)


def generate(assets_dir: Path, output: Path) -> None:
    files = sorted((path for path in assets_dir.glob("locales/**/*.ogg") if path.is_file()))
    if not files:
        raise SystemExit(f"no Ogg assets found under {assets_dir}")

    chunks = [
        "/* SPDX-License-Identifier: Apache-2.0 */",
        "/* Generated by projects/mybot/scripts/generate_assets_c.py. */",
        "/* Do not edit this file manually; regenerate it when assets change. */",
        "",
        '#include "mybot_assets.h"',
        "",
        "#include <string.h>",
        "",
    ]
    entries = []
    for path in files:
        rel = path.relative_to(assets_dir).as_posix()
        symbol = c_identifier(rel)
        data = path.read_bytes()
        chunks.extend([
            f"static const uint8_t {symbol}[] = {{",
            emit_bytes(data),
            "};",
            "",
        ])
        entries.append((f"mybot/assets/{rel}", symbol, len(data)))

    chunks.extend([
        "typedef struct mybot_asset_entry_s {",
        "    const char *path;",
        "    const uint8_t *data;",
        "    size_t size;",
        "} mybot_asset_entry_t;",
        "",
        "static const mybot_asset_entry_t s_assets[] = {",
    ])
    chunks.extend(
        f'    {{"{path}", {symbol}, sizeof({symbol})}},' for path, symbol, _ in entries
    )
    chunks.extend([
        "};",
        "",
        "static const char *asset_key(const char *path) {",
        '    const char *key = strstr(path, "mybot/assets/");',
        "    return key ? key : path;",
        "}",
        "",
        "int mybot_asset_find(const char *path, mybot_asset_t *asset) {",
        "    const char *key;",
        "    size_t i;",
        "",
        "    if (!path || !asset) {",
        "        return -1;",
        "    }",
        "    key = asset_key(path);",
        "    for (i = 0; i < sizeof(s_assets) / sizeof(s_assets[0]); ++i) {",
        "        if (strcmp(key, s_assets[i].path) == 0) {",
        "            asset->data = s_assets[i].data;",
        "            asset->size = s_assets[i].size;",
        "            return 0;",
        "        }",
        "    }",
        "    asset->data = NULL;",
        "    asset->size = 0;",
        "    return -1;",
        "}",
        "",
    ])

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(chunks), encoding="utf-8")
    print(f"generated {len(files)} assets ({sum(size for _, _, size in entries)} bytes) -> {output}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("assets_dir", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.assets_dir, args.output)


if __name__ == "__main__":
    main()
